apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: kbugger
spec:
 template:
  spec:
   containers:
    - image: ko://github.com/JeffNeff/kBugger/cmd/kBugger
      env:
        - name: EVENT_ID
          value: "io.kbugger.test"
        - name: EVENT_SOURCE
          value: "kbugger"
        - name: EVENT_SUBJECT
          value: "kbugger.subject"
        - name: EVENT_TYPE
          value: "kbugger.subject"
        - name: EVENT_DATA
          value: '{"test":"data"}'
        - name: TIMEOUT
          value: "20"
          # UPDATE THIS TO REFLECT THE BROKER OR TARGET YOU WANT TO SEND EVENTS TO 
        - name: K_SINK
          value: "http://broker-ingress.knative-eventing.svc.cluster.local/test/default"
